//! Warm container pool for the code-execution tool.
//!
//! Running untrusted, model-authored code safely means a fresh, hardened, network
//! -filtered container per execution. Creating one cold per call costs hundreds of
//! ms; to hide that, we keep `code_exec_pool_size` pre-warmed containers idle and
//! borrow one per run (`<runtime> exec`, ~tens of ms). Each container serves
//! **exactly one** execution: after the run it is destroyed and a replacement is
//! spun up in the background, so no filesystem state, leftover processes, or egress
//! state ever leak between runs.
//!
//! The pool is long-lived shared state (it lives in `AppState`, not in the
//! per-request `ToolRegistry`) and is cheaply cloneable (`Arc` inside).
//!
//! Testability: all container operations go through the [`ContainerBackend`] trait,
//! so the pool's borrow/recycle/concurrency logic is unit-tested with an in-memory
//! mock — no real containers, no Docker/Podman in CI. The trait uses boxed futures
//! (rather than `async fn`) so it stays object-safe for `Arc<dyn ContainerBackend>`.

use std::collections::VecDeque;
use std::future::Future;
use std::pin::Pin;
use std::process::Command as StdCommand;
use std::process::Stdio;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use tokio::io::{AsyncRead, AsyncReadExt, AsyncWriteExt};
use tokio::process::Command;
use tokio::sync::Semaphore;
use tokio_util::sync::CancellationToken;

use crate::config::Config;

/// A boxed, `Send` future — the object-safe return shape for [`ContainerBackend`].
type PoolFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// How a lane's containers attach to the network — the only difference between the
/// two code-exec tools. `None` (no internet at all) backs the offline `code_exec`
/// tool; `Named`/`RuntimeDefault` back the internet-capable `code_exec_online`.
#[derive(Debug, Clone)]
pub enum NetworkMode {
    /// `--network none`: no networking, not even loopback to other containers.
    None,
    /// `--network <name>`: a deployment-configured, egress-firewalled network.
    Named(String),
    /// No `--network` flag: the runtime default network (unfiltered — dev/test).
    RuntimeDefault,
}

impl NetworkMode {
    /// Resolve the online lane's mode from config: the firewalled network when one
    /// is set, otherwise the runtime default (documented as dev/test only).
    fn online(cfg: &Config) -> Self {
        match &cfg.code_exec_network {
            Some(n) => NetworkMode::Named(n.clone()),
            None => NetworkMode::RuntimeDefault,
        }
    }
}

/// Captured result of one code execution.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ExecOutput {
    pub stdout: String,
    pub stderr: String,
    /// Process exit code, when the process exited normally.
    pub exit_code: Option<i32>,
    /// The run hit the wall-clock timeout and was killed.
    pub timed_out: bool,
    /// Output exceeded `code_exec_output_chars` and was truncated.
    pub truncated: bool,
}

impl ExecOutput {
    fn timed_out(secs: u64) -> Self {
        ExecOutput {
            stdout: String::new(),
            stderr: format!("execution timed out after {secs}s"),
            exit_code: None,
            timed_out: true,
            truncated: false,
        }
    }
}

/// A handle to one pooled container. Cheap (just the container name); the runtime
/// owns the actual process.
#[derive(Debug, Clone)]
pub struct Container {
    pub name: String,
}

/// Container-name prefix shared by every container this pool starts. Names are
/// generated by the *pool* (not the backend) so an abandoned spawn can still be
/// reaped by name, and so a startup sweep can find a dead process's leftovers.
const NAME_PREFIX: &str = "phantasm-codeexec-";

/// A fresh, unique container name under [`NAME_PREFIX`].
fn fresh_name() -> String {
    format!("{NAME_PREFIX}{}", uuid::Uuid::new_v4().simple())
}

/// The container operations the pool needs, behind a trait so tests can substitute
/// an in-memory mock. Never panics; every fallible step returns `Err(String)` which
/// the pool surfaces as a non-fatal tool message.
pub trait ContainerBackend: Send + Sync {
    /// Start a fresh, hardened, idle container under `name` and return a handle
    /// to it. The caller picks the name so it can clean up by name if this
    /// future is dropped mid-spawn.
    fn spawn_container<'a>(
        &'a self,
        cfg: &'a Config,
        name: &'a str,
    ) -> PoolFuture<'a, Result<Container, String>>;
    /// Force-remove a container (and everything running in it). Idempotent.
    fn destroy<'a>(&'a self, c: &'a Container) -> PoolFuture<'a, Result<(), String>>;
    /// Run `code` in language `language` inside an existing container, returning its
    /// captured (and capped) output.
    fn exec<'a>(
        &'a self,
        c: &'a Container,
        language: &'a str,
        code: &'a str,
        cfg: &'a Config,
    ) -> PoolFuture<'a, Result<ExecOutput, String>>;
}

struct PoolInner {
    cfg: Arc<Config>,
    backend: Arc<dyn ContainerBackend>,
    /// Pre-warmed, idle containers waiting to be borrowed. Never grows past
    /// `cfg.code_exec_pool_size`.
    ready: Mutex<VecDeque<Container>>,
    /// Bounds concurrent executions (== pool size). A borrower past the limit
    /// awaits a free permit rather than spawning unboundedly.
    slots: Semaphore,
}

impl PoolInner {
    fn take_ready(&self) -> Option<Container> {
        self.ready.lock().expect("ready lock").pop_front()
    }

    fn pool_size(&self) -> usize {
        self.cfg.code_exec_pool_size
    }
}

/// A warm pool of one-shot execution containers. Clone is cheap (shared `Arc`).
#[derive(Clone)]
pub struct CodeExecPool(Arc<PoolInner>);

impl CodeExecPool {
    /// Build one production lane (shelling out to `cfg.code_exec_runtime` with the
    /// given `network` mode) and kick off background warm-up. Returns `Err` only on
    /// a clearly-unusable config; warm-up failures are non-fatal (logged) — the pool
    /// still serves via cold fallback.
    pub fn new(cfg: Arc<Config>, network: NetworkMode) -> Result<Self, String> {
        validate_sandbox_config(&cfg)?;
        let backend = Arc::new(PodmanBackend::new(cfg.code_exec_runtime.clone(), network));
        let pool = Self::with_backend(cfg, backend);
        pool.warm();
        Ok(pool)
    }

    /// Construct a pool over an arbitrary backend without warming it. The seam used
    /// by tests (with a mock backend) and by [`new`](Self::new).
    pub fn with_backend(cfg: Arc<Config>, backend: Arc<dyn ContainerBackend>) -> Self {
        let n = cfg.code_exec_pool_size.max(1);
        CodeExecPool(Arc::new(PoolInner {
            backend,
            ready: Mutex::new(VecDeque::with_capacity(n)),
            slots: Semaphore::new(n),
            cfg,
        }))
    }

    /// Spawn `pool_size` containers in the background and park them as ready. Each
    /// is independent; failures just leave the pool below target (cold fallback
    /// covers the gap).
    pub fn warm(&self) {
        for _ in 0..self.0.pool_size() {
            let inner = self.0.clone();
            tokio::spawn(async move {
                match inner
                    .backend
                    .spawn_container(&inner.cfg, &fresh_name())
                    .await
                {
                    Ok(c) => park_ready(&inner, c),
                    Err(e) => tracing::warn!(error = %e, "code-exec warm-up: container failed"),
                }
            });
        }
    }

    /// Run `code` once. Borrows a ready container (or cold-spawns one if the pool is
    /// still warming / drained), executes with a wall-clock timeout, and recycles
    /// the container afterwards regardless of outcome. `cancel` aborts an in-flight
    /// run; the container is still recycled, so no orphaned work survives.
    pub async fn execute(
        &self,
        language: &str,
        code: &str,
        cancel: &CancellationToken,
    ) -> Result<ExecOutput, String> {
        let inner = &self.0;
        // Backpressure: at most `pool_size` executions run at once.
        let _permit = inner
            .slots
            .acquire()
            .await
            .map_err(|_| "code-exec pool is shut down".to_string())?;

        let timeout = Duration::from_secs(inner.cfg.code_exec_timeout_s.max(1));

        // Borrow a warm container, or cold-spawn one when the pool is still
        // warming/drained. The cold spawn is bounded by the wall-clock timeout and
        // cancel too: a wedged runtime must not hang the call indefinitely while
        // holding a slot permit (it previously awaited the spawn outside any bound).
        // On an abort, dropping the spawn future only kills the podman *client*;
        // the daemon-side detached container may already exist under `name`, so a
        // best-effort remove-by-name runs in the background.
        let container = match inner.take_ready() {
            Some(c) => c,
            None => {
                let name = fresh_name();
                tokio::select! {
                    c = inner.backend.spawn_container(&inner.cfg, &name) => c?,
                    _ = tokio::time::sleep(timeout) => {
                        self.spawn_abort_cleanup(name);
                        return Ok(ExecOutput::timed_out(inner.cfg.code_exec_timeout_s))
                    }
                    _ = cancel.cancelled() => {
                        self.spawn_abort_cleanup(name);
                        return Err("cancelled".to_string())
                    }
                }
            }
        };

        let result = tokio::select! {
            r = inner.backend.exec(&container, language, code, &inner.cfg) => r,
            _ = tokio::time::sleep(timeout) => Ok(ExecOutput::timed_out(inner.cfg.code_exec_timeout_s)),
            _ = cancel.cancelled() => Err("cancelled".to_string()),
        };

        // Always recycle: a completed, timed-out, or cancelled container is
        // destroyed (force-killing any orphaned process) and replaced off the hot
        // path. Each container thus serves exactly one execution.
        self.spawn_recycle(container);
        result
    }

    /// Destroy a used container and, if the pool is below target, spin up a
    /// replacement — all in the background so the caller never waits on it.
    fn spawn_recycle(&self, used: Container) {
        let inner = self.0.clone();
        tokio::spawn(async move {
            let _ = inner.backend.destroy(&used).await;
            let below_target = inner.ready.lock().expect("ready lock").len() < inner.pool_size();
            if !below_target {
                return;
            }
            match inner
                .backend
                .spawn_container(&inner.cfg, &fresh_name())
                .await
            {
                Ok(fresh) => park_ready(&inner, fresh),
                Err(e) => tracing::warn!(error = %e, "code-exec recycle: replacement failed"),
            }
        });
    }

    /// Best-effort background removal of a container whose cold spawn was
    /// abandoned (timeout/cancel dropped the spawn future). `destroy` is
    /// idempotent, so it is harmless when the container never came to exist.
    fn spawn_abort_cleanup(&self, name: String) {
        let inner = self.0.clone();
        tokio::spawn(async move {
            let _ = inner.backend.destroy(&Container { name }).await;
        });
    }
}

/// The two code-exec lanes, each its own warm pool: `offline` runs with no network
/// (backs the `code_exec` tool, always available) and `online` runs with internet
/// via the egress-filtered network (backs `code_exec_online`, offered when web
/// access is on). Clone is cheap (both pools are `Arc`-backed).
#[derive(Clone)]
pub struct CodeExecPools {
    pub offline: CodeExecPool,
    pub online: CodeExecPool,
}

impl CodeExecPools {
    /// Build both lanes and start warming them. The offline lane uses
    /// `--network none`; the online lane uses the configured egress-filtered
    /// network. A missing or uninspectable online network fails closed so the
    /// tool is not advertised.
    pub fn new(cfg: Arc<Config>) -> Result<Self, String> {
        deployment_preflight(&cfg)?;
        // Reap idle containers stranded by a previous orchestrator process
        // *before* either pool starts warming, so the sweep can never race our
        // own fresh containers.
        sweep_stale_containers(&cfg.code_exec_runtime);
        let offline = CodeExecPool::new(cfg.clone(), NetworkMode::None)?;
        let online = CodeExecPool::new(cfg.clone(), NetworkMode::online(&cfg))?;
        Ok(CodeExecPools { offline, online })
    }
}

/// Remove `phantasm-codeexec-*` containers left behind by a previous process.
/// The pool never reaps its warm containers on shutdown, so every restart would
/// otherwise strand `pool_size × 2` idle containers. Best-effort and
/// synchronous (runs once at startup, before warm-up): failures are logged and
/// never block or fail startup.
fn sweep_stale_containers(runtime: &str) {
    let list = StdCommand::new(runtime)
        .args(["ps", "-aq", "--filter", &format!("name={NAME_PREFIX}")])
        .output();
    let ids: Vec<String> = match list {
        Ok(out) if out.status.success() => String::from_utf8_lossy(&out.stdout)
            .split_whitespace()
            .map(str::to_string)
            .collect(),
        Ok(out) => {
            let detail = String::from_utf8_lossy(&out.stderr).trim().to_string();
            tracing::warn!(error = %detail, "code-exec sweep: cannot list stale containers");
            return;
        }
        Err(e) => {
            tracing::warn!(error = %e, "code-exec sweep: cannot run {runtime}");
            return;
        }
    };
    if ids.is_empty() {
        return;
    }
    match StdCommand::new(runtime)
        .args(["rm", "-f"])
        .args(&ids)
        .output()
    {
        Ok(out) if out.status.success() => {
            tracing::info!(
                count = ids.len(),
                "code-exec sweep: removed stale containers"
            );
        }
        Ok(out) => {
            let detail = String::from_utf8_lossy(&out.stderr).trim().to_string();
            tracing::warn!(error = %detail, "code-exec sweep: removal failed");
        }
        Err(e) => tracing::warn!(error = %e, "code-exec sweep: removal failed"),
    }
}

/// Verify that a code-exec deployment is constrained enough to advertise. This
/// is intentionally fail-closed: if the runtime, image, network, or hardening
/// config cannot be proven present, the tool is disabled rather than offered to
/// the model.
pub fn deployment_preflight(cfg: &Config) -> Result<(), String> {
    validate_sandbox_config(cfg)?;
    let network = cfg
        .code_exec_network
        .as_deref()
        .ok_or_else(|| "CODE_EXEC_NETWORK is required when TOOL_CODE_EXEC=true".to_string())?;
    run_probe(&cfg.code_exec_runtime, ["--version"], "container runtime")?;
    run_probe(
        &cfg.code_exec_runtime,
        ["image", "inspect", cfg.code_exec_image.as_str()],
        "code-exec image",
    )?;
    run_probe(
        &cfg.code_exec_runtime,
        ["network", "inspect", network],
        "code-exec network",
    )?;
    Ok(())
}

fn validate_sandbox_config(cfg: &Config) -> Result<(), String> {
    if cfg.code_exec_runtime.trim().is_empty() {
        return Err("CODE_EXEC_RUNTIME is empty".into());
    }
    if cfg.code_exec_image.trim().is_empty() {
        return Err("CODE_EXEC_IMAGE is empty".into());
    }
    if cfg.code_exec_memory.trim().is_empty() || cfg.code_exec_memory.trim() == "0" {
        return Err("CODE_EXEC_MEMORY must set a non-zero memory cap".into());
    }
    let cpus: f64 = cfg
        .code_exec_cpus
        .trim()
        .parse()
        .map_err(|_| "CODE_EXEC_CPUS must be a positive number".to_string())?;
    if !(cpus.is_finite() && cpus > 0.0) {
        return Err("CODE_EXEC_CPUS must be a positive number".into());
    }
    if cfg.code_exec_pids_limit == 0 {
        return Err("CODE_EXEC_PIDS_LIMIT must be greater than zero".into());
    }
    if user_is_root(&cfg.code_exec_run_user) {
        return Err("CODE_EXEC_USER must not run code as root".into());
    }

    let args = run_container_args(cfg, "preflight", &NetworkMode::None);
    for required in ["--read-only", "--cap-drop", "--security-opt", "--user"] {
        if !args.iter().any(|arg| arg == required) {
            return Err(format!("code-exec run args are missing {required}"));
        }
    }
    if args.iter().any(|arg| arg == "--privileged") {
        return Err("code-exec containers must not run privileged".into());
    }
    if !has_arg_pair(&args, "--cap-drop", "ALL") {
        return Err("code-exec containers must drop all capabilities".into());
    }
    if !has_arg_pair(&args, "--security-opt", "no-new-privileges") {
        return Err("code-exec containers must set no-new-privileges".into());
    }
    Ok(())
}

fn run_probe<'a>(
    runtime: &str,
    args: impl IntoIterator<Item = &'a str>,
    what: &str,
) -> Result<(), String> {
    let out = StdCommand::new(runtime)
        .args(args)
        .output()
        .map_err(|e| format!("{what} probe failed to start `{runtime}`: {e}"))?;
    if !out.status.success() {
        let detail = String::from_utf8_lossy(&out.stderr).trim().to_string();
        return Err(format!("{what} probe failed: {detail}"));
    }
    Ok(())
}

fn user_is_root(raw: &str) -> bool {
    let mut parts = raw.trim().split(':');
    let user = parts.next().unwrap_or_default();
    let group = parts.next();
    user.is_empty()
        || user == "0"
        || user.eq_ignore_ascii_case("root")
        || group.is_some_and(|g| g == "0" || g.eq_ignore_ascii_case("root"))
}

fn has_arg_pair(args: &[String], key: &str, value: &str) -> bool {
    args.windows(2)
        .any(|pair| pair[0] == key && pair[1] == value)
}

fn run_container_args(cfg: &Config, name: &str, network: &NetworkMode) -> Vec<String> {
    let mut args = vec![
        "run".into(),
        "-d".into(),
        "--name".into(),
        name.into(),
        "--memory".into(),
        cfg.code_exec_memory.clone(),
        "--cpus".into(),
        cfg.code_exec_cpus.clone(),
        "--pids-limit".into(),
        cfg.code_exec_pids_limit.to_string(),
        "--read-only".into(),
        "--tmpfs".into(),
        "/tmp:rw,size=64m".into(),
        "--user".into(),
        cfg.code_exec_run_user.clone(),
        "--cap-drop".into(),
        "ALL".into(),
        "--security-opt".into(),
        "no-new-privileges".into(),
    ];
    match network {
        NetworkMode::None => {
            args.push("--network".into());
            args.push("none".into());
        }
        NetworkMode::Named(net) => {
            args.push("--network".into());
            args.push(net.clone());
        }
        NetworkMode::RuntimeDefault => {}
    }
    args.push(cfg.code_exec_image.clone());
    args
}

/// Park a freshly-started container as ready, unless the ready queue is already at
/// target (which can happen under churn) — in which case destroy the surplus so the
/// pool never exceeds `pool_size` idle containers.
fn park_ready(inner: &Arc<PoolInner>, c: Container) {
    let surplus = {
        let mut q = inner.ready.lock().expect("ready lock");
        if q.len() < inner.pool_size() {
            q.push_back(c);
            None
        } else {
            Some(c)
        }
    };
    if let Some(extra) = surplus {
        let inner = inner.clone();
        tokio::spawn(async move {
            let _ = inner.backend.destroy(&extra).await;
        });
    }
}

/// Production backend: shells out to `podman`/`docker`.
pub struct PodmanBackend {
    runtime: String,
    network: NetworkMode,
}

impl PodmanBackend {
    pub fn new(runtime: String, network: NetworkMode) -> Self {
        PodmanBackend { runtime, network }
    }
}

impl ContainerBackend for PodmanBackend {
    fn spawn_container<'a>(
        &'a self,
        cfg: &'a Config,
        name: &'a str,
    ) -> PoolFuture<'a, Result<Container, String>> {
        Box::pin(async move {
            let mut cmd = Command::new(&self.runtime);
            cmd.args(run_container_args(cfg, name, &self.network));
            // If the spawn future is dropped (cold-spawn timeout/cancel), kill the
            // `run` client rather than leaving it wedged against a stuck runtime.
            cmd.kill_on_drop(true);

            let out = cmd
                .output()
                .await
                .map_err(|e| format!("cannot start {}: {e}", self.runtime))?;
            if !out.status.success() {
                return Err(format!(
                    "container start failed: {}",
                    String::from_utf8_lossy(&out.stderr).trim()
                ));
            }
            Ok(Container {
                name: name.to_string(),
            })
        })
    }

    fn destroy<'a>(&'a self, c: &'a Container) -> PoolFuture<'a, Result<(), String>> {
        Box::pin(async move {
            // `-f` force-removes a running container (and its processes). Best
            // effort: a missing container ("no such container") is fine.
            let _ = Command::new(&self.runtime)
                .arg("rm")
                .arg("-f")
                .arg(&c.name)
                .output()
                .await;
            Ok(())
        })
    }

    fn exec<'a>(
        &'a self,
        c: &'a Container,
        language: &'a str,
        code: &'a str,
        cfg: &'a Config,
    ) -> PoolFuture<'a, Result<ExecOutput, String>> {
        Box::pin(async move {
            let mut child = Command::new(&self.runtime)
                .arg("exec")
                .arg("-i")
                .arg(&c.name)
                .arg("/usr/local/bin/run-code")
                .arg(language)
                .stdin(Stdio::piped())
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                // If the future is dropped (timeout/cancel), kill the `exec` client;
                // the container itself is reaped separately by recycle.
                .kill_on_drop(true)
                .spawn()
                .map_err(|e| format!("cannot run {} exec: {e}", self.runtime))?;

            // Feed the source on stdin from a task so output reads start immediately
            // — a script that floods stdout can't deadlock the stdin write.
            if let Some(mut stdin) = child.stdin.take() {
                let data = code.as_bytes().to_vec();
                tokio::spawn(async move {
                    let _ = stdin.write_all(&data).await;
                    let _ = stdin.shutdown().await;
                });
            }

            let stdout = child.stdout.take().expect("piped stdout");
            let stderr = child.stderr.take().expect("piped stderr");
            let cap = cfg.code_exec_output_chars;
            let (so, se, status) = tokio::join!(
                read_capped(stdout, cap),
                read_capped(stderr, cap),
                child.wait(),
            );
            let status = status.map_err(|e| format!("exec wait failed: {e}"))?;
            Ok(ExecOutput {
                stdout: so.0,
                stderr: se.0,
                exit_code: status.code(),
                timed_out: false,
                truncated: so.1 || se.1,
            })
        })
    }
}

/// Read a stream, keeping at most `cap` bytes but always draining to EOF so the
/// child can finish (and our memory stays bounded). Returns the kept text and
/// whether anything was dropped.
async fn read_capped<R: AsyncRead + Unpin>(mut r: R, cap: usize) -> (String, bool) {
    let mut kept: Vec<u8> = Vec::new();
    let mut scratch = [0u8; 8192];
    let mut truncated = false;
    loop {
        match r.read(&mut scratch).await {
            Ok(0) => break,
            Ok(n) => {
                if kept.len() < cap {
                    let take = (cap - kept.len()).min(n);
                    kept.extend_from_slice(&scratch[..take]);
                    if take < n {
                        truncated = true;
                    }
                } else {
                    truncated = true;
                }
            }
            Err(_) => break,
        }
    }
    // The byte-level cap can land mid-character; drop a trailing partial UTF-8
    // sequence so the cut falls on a char boundary rather than becoming a `�`.
    trim_trailing_partial_utf8(&mut kept);
    (String::from_utf8_lossy(&kept).into_owned(), truncated)
}

/// Drop an incomplete trailing UTF-8 sequence from `buf` — the continuation
/// bytes plus their lead byte when the full sequence isn't present. A complete
/// trailing char is kept; an empty buffer (or one ending in a complete char) is
/// left unchanged. Mid-buffer invalid bytes are left for `from_utf8_lossy`.
fn trim_trailing_partial_utf8(buf: &mut Vec<u8>) {
    // Walk back over continuation bytes (0b10xx_xxxx) to the sequence's lead.
    let mut lead = buf.len();
    while lead > 0 && (buf[lead - 1] & 0xC0) == 0x80 {
        lead -= 1;
    }
    if lead == 0 {
        return;
    }
    let first = buf[lead - 1];
    let expected = if first < 0x80 {
        1
    } else if first >> 5 == 0b110 {
        2
    } else if first >> 4 == 0b1110 {
        3
    } else if first >> 3 == 0b11110 {
        4
    } else {
        1 // stray/invalid lead byte — treat as a single byte, leave to lossy
    };
    if buf.len() - (lead - 1) < expected {
        buf.truncate(lead - 1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    /// In-memory backend: counts spawn/destroy, returns canned exec output, and can
    /// gate `exec` on a barrier to test concurrency.
    #[derive(Default)]
    struct MockBackend {
        spawned: AtomicUsize,
        destroyed: AtomicUsize,
        /// Names passed to `destroy`, so tests can check *which* container was
        /// reaped (e.g. the abort-cleanup of an abandoned cold spawn).
        destroyed_names: Mutex<Vec<String>>,
        execed: AtomicUsize,
        fail_spawn: bool,
        hold: Option<Arc<tokio::sync::Notify>>,
        /// When set, `spawn_container` blocks on it — models a wedged runtime so a
        /// cold spawn's timeout/cancel handling can be tested.
        spawn_hold: Option<Arc<tokio::sync::Notify>>,
    }

    impl ContainerBackend for MockBackend {
        fn spawn_container<'a>(
            &'a self,
            _cfg: &'a Config,
            name: &'a str,
        ) -> PoolFuture<'a, Result<Container, String>> {
            Box::pin(async move {
                if let Some(gate) = &self.spawn_hold {
                    gate.notified().await;
                }
                if self.fail_spawn {
                    return Err("spawn failed".into());
                }
                self.spawned.fetch_add(1, Ordering::SeqCst);
                Ok(Container {
                    name: name.to_string(),
                })
            })
        }

        fn destroy<'a>(&'a self, c: &'a Container) -> PoolFuture<'a, Result<(), String>> {
            Box::pin(async move {
                self.destroyed.fetch_add(1, Ordering::SeqCst);
                self.destroyed_names
                    .lock()
                    .expect("names lock")
                    .push(c.name.clone());
                Ok(())
            })
        }

        fn exec<'a>(
            &'a self,
            _c: &'a Container,
            language: &'a str,
            _code: &'a str,
            _cfg: &'a Config,
        ) -> PoolFuture<'a, Result<ExecOutput, String>> {
            Box::pin(async move {
                self.execed.fetch_add(1, Ordering::SeqCst);
                if let Some(hold) = &self.hold {
                    hold.notified().await;
                }
                Ok(ExecOutput {
                    stdout: format!("ran {language}"),
                    ..Default::default()
                })
            })
        }
    }

    fn cfg(pool_size: usize) -> Arc<Config> {
        let mut c = crate::config::tests_support::minimal();
        c.code_exec_enabled = true;
        c.code_exec_pool_size = pool_size;
        c.code_exec_network = Some("phantasm-code-exec".into());
        Arc::new(c)
    }

    fn raw_cfg() -> Config {
        let mut c = crate::config::tests_support::minimal();
        c.code_exec_enabled = true;
        c.code_exec_network = Some("phantasm-code-exec".into());
        c
    }

    /// Drain the background recycle/warm tasks so their effects are observable.
    async fn settle() {
        for _ in 0..20 {
            tokio::task::yield_now().await;
        }
    }

    #[tokio::test]
    async fn cold_falls_back_when_empty_then_runs() {
        let backend = Arc::new(MockBackend::default());
        let pool = CodeExecPool::with_backend(cfg(2), backend.clone());
        // with_backend does not warm, so the ready queue starts empty.
        let out = pool
            .execute("python", "print(1)", &CancellationToken::new())
            .await
            .unwrap();
        assert_eq!(out.stdout, "ran python");
        assert!(backend.spawned.load(Ordering::SeqCst) >= 1);
    }

    #[tokio::test]
    async fn each_run_recycles_its_container() {
        let backend = Arc::new(MockBackend::default());
        let pool = CodeExecPool::with_backend(cfg(2), backend.clone());
        pool.execute("bash", "echo hi", &CancellationToken::new())
            .await
            .unwrap();
        settle().await;
        // The borrowed container was destroyed and a replacement spawned.
        assert_eq!(backend.destroyed.load(Ordering::SeqCst), 1);
        assert!(
            backend.spawned.load(Ordering::SeqCst) >= 2,
            "one cold container + one replacement"
        );
    }

    #[test]
    fn trims_partial_trailing_utf8_only() {
        // '€' is E2 82 AC; a cap keeping just its first two bytes drops it whole.
        let mut buf = vec![b'a', 0xE2, 0x82];
        trim_trailing_partial_utf8(&mut buf);
        assert_eq!(buf, vec![b'a']);
        // A complete trailing multibyte char is preserved untouched.
        let mut whole = vec![0xE2, 0x82, 0xAC];
        trim_trailing_partial_utf8(&mut whole);
        assert_eq!(whole, vec![0xE2, 0x82, 0xAC]);
        // Plain ASCII is left alone.
        let mut ascii = b"hello".to_vec();
        trim_trailing_partial_utf8(&mut ascii);
        assert_eq!(ascii, b"hello");
    }

    #[tokio::test(start_paused = true)]
    async fn cold_spawn_timeout_does_not_hang() {
        // Empty pool (not warmed) + a runtime whose spawn never returns: execute
        // must hit the wall-clock timeout and free its slot, not block forever.
        let backend = Arc::new(MockBackend {
            spawn_hold: Some(Arc::new(tokio::sync::Notify::new())),
            ..Default::default()
        });
        let pool = CodeExecPool::with_backend(cfg(1), backend.clone());
        let out = pool
            .execute("python", "x", &CancellationToken::new())
            .await
            .unwrap();
        assert!(out.timed_out, "a wedged cold spawn must time out");
        // Slot was released, so a subsequent borrow can still proceed.
        assert_eq!(pool.0.slots.available_permits(), 1);
        // The abandoned spawn's container is reaped by name: the daemon-side
        // container may exist even though the spawn future was dropped.
        settle().await;
        assert_eq!(backend.destroyed.load(Ordering::SeqCst), 1);
        let names = backend.destroyed_names.lock().unwrap();
        assert!(
            names[0].starts_with(NAME_PREFIX),
            "cleanup must target the pre-generated name, got {names:?}"
        );
    }

    #[tokio::test]
    async fn cancelled_cold_spawn_cleans_up_its_container() {
        let backend = Arc::new(MockBackend {
            spawn_hold: Some(Arc::new(tokio::sync::Notify::new())),
            ..Default::default()
        });
        let pool = CodeExecPool::with_backend(cfg(1), backend.clone());
        let cancel = CancellationToken::new();
        let token = cancel.clone();
        let handle = {
            let pool = pool.clone();
            tokio::spawn(async move { pool.execute("python", "x", &token).await })
        };
        settle().await;
        cancel.cancel();
        assert_eq!(handle.await.unwrap().unwrap_err(), "cancelled");
        settle().await;
        assert_eq!(
            backend.destroyed.load(Ordering::SeqCst),
            1,
            "a cancelled cold spawn still removes its (possibly created) container"
        );
    }

    #[tokio::test]
    async fn spawn_failure_surfaces_as_error_not_panic() {
        let backend = Arc::new(MockBackend {
            fail_spawn: true,
            ..Default::default()
        });
        let pool = CodeExecPool::with_backend(cfg(1), backend);
        let err = pool
            .execute("python", "x", &CancellationToken::new())
            .await
            .unwrap_err();
        assert_eq!(err, "spawn failed");
    }

    #[tokio::test]
    async fn cancellation_returns_cancelled_and_recycles() {
        let hold = Arc::new(tokio::sync::Notify::new());
        let backend = Arc::new(MockBackend {
            hold: Some(hold.clone()),
            ..Default::default()
        });
        let pool = CodeExecPool::with_backend(cfg(1), backend.clone());
        let cancel = CancellationToken::new();
        let token = cancel.clone();
        let handle = {
            let pool = pool.clone();
            tokio::spawn(async move { pool.execute("python", "x", &token).await })
        };
        // Let exec start (and block on the barrier), then cancel.
        settle().await;
        cancel.cancel();
        let res = handle.await.unwrap();
        assert_eq!(res.unwrap_err(), "cancelled");
        settle().await;
        assert_eq!(
            backend.destroyed.load(Ordering::SeqCst),
            1,
            "cancelled run still recycles its container"
        );
    }

    #[tokio::test]
    async fn concurrency_is_capped_at_pool_size() {
        let hold = Arc::new(tokio::sync::Notify::new());
        let backend = Arc::new(MockBackend {
            hold: Some(hold.clone()),
            ..Default::default()
        });
        let pool = CodeExecPool::with_backend(cfg(1), backend.clone());
        assert_eq!(pool.0.slots.available_permits(), 1);

        // First execution acquires the only permit and blocks on the barrier.
        let p1 = pool.clone();
        let h1 =
            tokio::spawn(async move { p1.execute("python", "a", &CancellationToken::new()).await });
        settle().await;
        assert_eq!(backend.execed.load(Ordering::SeqCst), 1);
        assert_eq!(
            pool.0.slots.available_permits(),
            0,
            "the permit is held for the duration of the run"
        );

        // Release the run; the permit returns to the pool.
        hold.notify_waiters();
        let _ = h1.await.unwrap();
        settle().await;
        assert_eq!(pool.0.slots.available_permits(), 1);
    }

    #[test]
    fn sandbox_config_rejects_root_user() {
        let mut c = raw_cfg();
        c.code_exec_run_user = "0:0".into();
        let err = validate_sandbox_config(&c).unwrap_err();
        assert!(err.contains("must not run code as root"));
    }

    #[test]
    fn deployment_preflight_requires_explicit_online_network() {
        let mut c = raw_cfg();
        c.code_exec_network = None;
        let err = deployment_preflight(&c).unwrap_err();
        assert!(err.contains("CODE_EXEC_NETWORK is required"));
    }

    #[test]
    fn run_args_include_hardening_without_privileged() {
        let c = raw_cfg();
        let args = run_container_args(&c, "name", &NetworkMode::None);
        assert!(has_arg_pair(&args, "--network", "none"));
        assert!(has_arg_pair(&args, "--cap-drop", "ALL"));
        assert!(has_arg_pair(&args, "--security-opt", "no-new-privileges"));
        assert!(args.iter().any(|arg| arg == "--read-only"));
        assert!(!args.iter().any(|arg| arg == "--privileged"));
    }
}
